### ISSUE TITLE
Moved to 404

### ISSUE THREAD

**Issue by dchest** [trevp/curve25519sigs#1]
Hi Trevor!

The link https://github.com/WhisperSystems/Specifications/blob/master/curve25519sigs.md doesn't work, do you know the new location for it?

Thanks!

**Comment by trevp** [comment]
Hi Dmitry,

I don't have a new public reference for this.  At some time this year I'll
release this and some other specs.

Looks like you can find the old text via Google cache, though.

Trevor

On Tue, Feb 16, 2016 at 10:08 AM, Dmitry Chestnykh <notifications@github.com

**Comment by dchest** [comment]
OK, thanks!
